### ISSUE TITLE
**TypeError: Cannot read properties of undefined (reading 'toUpperCase') در index-BDWYOqw1.js**

### ISSUE THREAD

**Issue by 0x-mhmdnzri** [orgamiryazdani/panel-admin#1]
### توضیحات:
هنگام اجرای برنامه، با یک خطای جاوااسکریپت روبرو شدم که باعث توقف عملکرد برنامه می‌شود. خطای مربوطه در فایل `index-BDWYOqw1.js` رخ می‌دهد و پیام خطا به صورت زیر است:

```
Uncaught TypeError: Cannot read properties of undefined (reading 'toUpperCase')
    at gK (index-BDWYOqw1.js:384:34502)
    at Wx (index-BDWYOqw1.js:38:17018)
    at Av (index-BDWYOqw1.js:40:3139)
    at DT (index-BDWYOqw1.js:40:2351)
    at Qb (index-BDWYOqw1.js:40:1893)
    at tN (index-BDWYOqw1.js:40:47351)
    at XT (index-BDWYOqw1.js:40:39790)
    at cM (index-BDWYOqw1.js:40:39718)
    at ip (index-BDWYOqw1.js:40:39570)
    at Uv (index-BDWYOqw1.js:40:35934)
```

### مراحل تولید باگ:
1. وارد صفحه داشبورد شدم
2. بعد از لودینگ خطا رخ داد
 
### انتظار:
برنامه بدون هیچ خطا اجرا شده و مقادیر `undefined` به درستی مدیریت شوند.

### رفتار فعلی:
هنگامی که برنامه به بخش خاصی از کد می‌رسد که نیاز به تبدیل به حروف بزرگ دارد، متغیر `undefined` است و منجر به خطای `TypeError` می‌شود.

### اسکرین‌شات:
![image](https://github.com/user-attachments/assets/bb6e1804-b7df-482a-909e-8aa74dc2addb)

---

### محیط:
- مرورگر:  Chrome Version 128.0.6613.138 (Official Build) (64-bit) 

- سیستم عامل: Windows 11
- نسخه برنامه: [Live Version On Vercel](https://panel-admin-ruby.vercel.app/)

---

لطفاً این باگ را بررسی کرده و راه‌حل یا به‌روزرسانی را ارائه دهید.

**Comment by orgamiryazdani** [comment]
سلام وقت بخیر
لطفا پول ریکوئست بزنین و چک کنین دوباره فکر میکنم رفع شده باشه 
همچنین خوشحال میشم اگه تغییراتی رو پروژه دادین یا بخشی رو توسعه دادین باهام به اشتراک بزارید
که روی همین نسخه هم مرج کنیم

**Comment by orgamiryazdani** [comment]
![Screenshot (23)](https://github.com/user-attachments/assets/8c6a4020-cdec-49e2-8fb7-b5bf5b96364c)

همچنین به api هم توجه داشته باشید
و در پروژه خودتون جایگذاری کنید

**Comment by eblomof** [comment]
روی نسخه لایو به مشکل خوردم
لوکال رو چک نکردم

**Comment by orgamiryazdani** [comment]
خب پروژه ای که توی ورسل اضافه کردید باید یک Environment Variables با این key و value هم واسش تعریف کنید که به درستی کار کنه

**Comment by orgamiryazdani** [comment]
متاسفانه لینک اشتباهی روی خود پروژه گذاشته شده بود 
و منم فک کردم شما یک نسخه از پروژه روجدا آنلاین کردید 
از این لینک وارد بشید
https://panel-admin-shop.vercel.app/
